// Code generated by "stringer -linecomment -type ESTAManCode"; DO NOT EDIT.

package artnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ESTAManUnknown-0]
	_ = x[ESTAManGlobal-65535]
}

const (
	_ESTAManCode_name_0 = "ESTAManUnknown"
	_ESTAManCode_name_1 = "ESTAManGlobal"
)

func (i ESTAManCode) String() string {
	switch {
	case i == 0:
		return _ESTAManCode_name_0
	case i == 65535:
		return _ESTAManCode_name_1
	default:
		return "ESTAManCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
