// Code generated by "stringer -linecomment -type OemCode"; DO NOT EDIT.

package artnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OemDMXHub-0]
	_ = x[OemGlobal-65535]
}

const (
	_OemCode_name_0 = "Manufacturer: Artistic Licence Engineering Ltd ProductName: Dmx Hub   NumDmxIn: 4 NumDmxOut: 4 DmxPortPhysical: y RdmSupported: n SupportEmail: support@ArtisticLicence.com SupportName: Wayne Howell CoWeb: http://www.ArtisticLicence.com"
	_OemCode_name_1 = "Manufacturer: Artistic Licence Engineering Ltd ProductName: OemGlobal NumDmxIn: 0 NumDmxOut: 0 DmxPortPhysical: n RdmSupported: n SupportEmail: support@ArtisticLicence.com SupportName: Wayne Howell CoWeb: http://www.ArtisticLicence.com"
)

func (i OemCode) String() string {
	switch {
	case i == 0:
		return _OemCode_name_0
	case i == 65535:
		return _OemCode_name_1
	default:
		return "OemCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
