// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package artnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpPoll-8192]
	_ = x[OpPollReply-8448]
	_ = x[OpDiagData-8960]
	_ = x[OpCommand-9216]
	_ = x[OpDataRequest-9984]
	_ = x[OpDataReply-10240]
	_ = x[OpDmx-20480]
	_ = x[OpNzs-20736]
	_ = x[OpSync-20992]
	_ = x[OpAddress-24576]
	_ = x[OpInput-28672]
	_ = x[OpTodRequest-32768]
	_ = x[OpTodData-33024]
	_ = x[OpTodControl-33280]
	_ = x[OpRdm-33536]
	_ = x[OpRdmSub-33792]
	_ = x[OpVideoSetup-40976]
	_ = x[OpVideoPalette-40992]
	_ = x[OpVideoData-41024]
	_ = x[OpMacMaster-61440]
	_ = x[OpMacSlave-61696]
	_ = x[OpFirmwareMaster-61952]
	_ = x[OpFirmwareReply-62208]
	_ = x[OpFileTnMaster-62464]
	_ = x[OpFileFnMaster-62720]
	_ = x[OpFileFnReply-62976]
	_ = x[OpIpProg-63488]
	_ = x[OpIpProgReply-63744]
	_ = x[OpMedia-36864]
	_ = x[OpMediaPatch-37120]
	_ = x[OpMediaControl-37376]
	_ = x[OpMediaContrlReply-37632]
	_ = x[OpTimeCode-38656]
	_ = x[OpTimeSync-38912]
	_ = x[OpTrigger-39168]
	_ = x[OpDirectory-39424]
	_ = x[OpDirectoryReply-39680]
}

const _OpCode_name = "OpPollOpPollReplyOpDiagDataOpCommandOpDataRequestOpDataReplyOpDmxOpNzsOpSyncOpAddressOpInputOpTodRequestOpTodDataOpTodControlOpRdmOpRdmSubOpMediaOpMediaPatchOpMediaControlOpMediaContrlReplyOpTimeCodeOpTimeSyncOpTriggerOpDirectoryOpDirectoryReplyOpVideoSetupOpVideoPaletteOpVideoDataOpMacMasterOpMacSlaveOpFirmwareMasterOpFirmwareReplyOpFileTnMasterOpFileFnMasterOpFileFnReplyOpIpProgOpIpProgReply"

var _OpCode_map = map[OpCode]string{
	8192:  _OpCode_name[0:6],
	8448:  _OpCode_name[6:17],
	8960:  _OpCode_name[17:27],
	9216:  _OpCode_name[27:36],
	9984:  _OpCode_name[36:49],
	10240: _OpCode_name[49:60],
	20480: _OpCode_name[60:65],
	20736: _OpCode_name[65:70],
	20992: _OpCode_name[70:76],
	24576: _OpCode_name[76:85],
	28672: _OpCode_name[85:92],
	32768: _OpCode_name[92:104],
	33024: _OpCode_name[104:113],
	33280: _OpCode_name[113:125],
	33536: _OpCode_name[125:130],
	33792: _OpCode_name[130:138],
	36864: _OpCode_name[138:145],
	37120: _OpCode_name[145:157],
	37376: _OpCode_name[157:171],
	37632: _OpCode_name[171:189],
	38656: _OpCode_name[189:199],
	38912: _OpCode_name[199:209],
	39168: _OpCode_name[209:218],
	39424: _OpCode_name[218:229],
	39680: _OpCode_name[229:245],
	40976: _OpCode_name[245:257],
	40992: _OpCode_name[257:271],
	41024: _OpCode_name[271:282],
	61440: _OpCode_name[282:293],
	61696: _OpCode_name[293:303],
	61952: _OpCode_name[303:319],
	62208: _OpCode_name[319:334],
	62464: _OpCode_name[334:348],
	62720: _OpCode_name[348:362],
	62976: _OpCode_name[362:375],
	63488: _OpCode_name[375:383],
	63744: _OpCode_name[383:396],
}

func (i OpCode) String() string {
	if str, ok := _OpCode_map[i]; ok {
		return str
	}
	return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
