log: etc/show-control.log
io:
  novation-launchpad-mini-mk3:
    enabled: true
    # OSX device name
    device: Launchpad Mini MK3 LPMiniMK3 MIDI
    # Debian device name (amidi -l)
    #device: Launchpad Mini MK3 MIDI 2
  webhook:
    enabled: true
    device: :8765
  console:
    enabled: true
